name: islam
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.1
  easy_localization: ^3.0.7
  http: ^1.2.2
  iconsax: ^0.0.8
  diacritic: ^0.1.5
  audioplayers: ^6.0.0
  just_audio: ^0.9.39
  intl: ^0.19.0
  video_player: ^2.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/islam.png
  android: true
  ios: true
  web: false


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/translations/
    - assets/azkar.json






  fonts:
    - family: Janna
      fonts:
        - asset: assets/fonts/janna.ttf

  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

